import { Inter } from 'next/font/google';

import { getServerSession } from 'next-auth/next';

import clsx from 'clsx';

import './globals.css';
import { authOptions } from 'src/app/api/auth/[...nextauth]/route';
import Providers from 'src/app/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const RootLayout = async ({ children }) => {
    const session = await getServerSession(authOptions);

    return (
        <html lang='en'>
            <body className={clsx(inter.className, process.env.NODE_ENV !== 'production' && 'debug-screens')}>
                <Providers session={session}>{children}</Providers>
            </body>
        </html>
    );
};

export default RootLayout;
