import { Inter } from 'next/font/google';

import './globals.css';
import clsx from 'clsx';
import Providers from 'src/app/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={clsx(inter.className, process.env.NODE_ENV !== 'production' && 'debug-screens')}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
